name: Déploiement site statique

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer tdewolff/minify
        run: |
          curl -L https://github.com/tdewolff/minify/releases/latest/download/minify_linux_amd64.tar.gz -o minify.tar.gz
          tar -xzf minify.tar.gz
          sudo mv minify /usr/local/bin/

      - name: Minifier HTML, CSS, JS
        working-directory: ./dailymenu
        run: |
          mkdir -p ../dist/images
          minify -o ../dist/index.html index.html
          minify -o ../dist/accessibilite.html accessibilite.html
          minify -o ../dist/menuweek.html menuweek.html
          minify -o ../dist/navbar.html navbar.html
          minify -o ../dist/tarifs.html tarifs.html
          cat css/*.css > ../dist/style.concat.css
          minify -o ../dist/style.css ../dist/style.concat.css
          minify -o ../dist/script.js script.js
          cp -r images/* ../dist/images/ || echo "Pas d'images à copier"

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
